apiVersion: v1
kind: Service
metadata:
  name: test-deployment-name-39
  namespace: test-namespace-39
  labels:
    app: test-deployment-name-39
spec:
  type: ClusterIP
  selector:
    app: test-deployment-name-39
  ports:
    - name: TCP
      protocol: TCP
      port: 80
      targetPort: 80
    - name: TCP
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-name-39
  namespace: test-namespace-39
  labels:
    app: test-deployment-name-39
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment-name-39
  template:
    metadata:
      labels:
        app: test-deployment-name-39
    spec:
      containers:
        - name: test-deployment-name-39-container
          image: docker.io/satyamp07/rabbitmq:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: 512MB
              cpu: 2M
            limits:
              memory: 512MB
              cpu: 2M
          env:
            - name: NODE_ENV
              value: production
            - name: API_KEY
              value: your-api-key-here
      imagePullSecrets:
        - name: scoutflo-registry-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-deployment-name-39
  namespace: test-namespace-39
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: docker-custom-service-test-test.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-deployment-name-39
                port:
                  number: 80
  tls:
    - hosts:
        - docker-custom-service-test-test.scoutflo.agency
      secretName: docker-custom-service-test-test-scoutflo-agency-tls
