apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-name-30
  namespace: test-namespace-30
  labels:
    app: test-deployment-name-30
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment-name-30
  template:
    metadata:
      labels:
        app: test-deployment-name-30
    spec:
      containers:
        - name: test-deployment-name-30-container
          image: https://docker.io/satyamp07/rabbitmq:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: 512MB
              cpu: 2M
            limits:
              memory: 512MB
              cpu: 2M
          env:
            - name: NODE_ENV
              value: production
            - name: API_KEY
              value: your-api-key-here
      imagePullSecrets:
        - name: scoutflo-certmanager-secret

---
apiVersion: v1
kind: Service
metadata:
  name: test-deployment-name-30
  namespace: test-namespace-30
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ipv6: 'false'
  labels:
    app: test-deployment-name-30
spec:
  type: ClusterIP
  selector:
    app: test-deployment-name-30
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-deployment-name-30
  namespace: test-namespace-30
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: test-deployment-name-30-mtqfj.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-deployment-name-30
                port:
                  number: 80
  tls:
    - hosts:
        - test-deployment-name-30-mtqfj.scoutflo.agency
      secretName: test-deployment-name-30-mtqfj-scoutflo-agency-tls
