apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-name-37
  namespace: test-namespace-37
  labels:
    app: test-deployment-name-37
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment-name-37
  template:
    metadata:
      labels:
        app: test-deployment-name-37
    spec:
      containers:
        - name: test-deployment-name-37-container
          image: docker.io/satyamp07/rabbitmq:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: 512MB
              cpu: 200m
            limits:
              memory: 512MB
              cpu: 2
          env:
            - name: NODE_ENV
              value: production
            - name: API_KEY
              value: your-api-key-here
      imagePullSecrets:
        - name: scoutflo-certmanager-secret

---
apiVersion: v1
kind: Service
metadata:
  name: test-deployment-name-37
  namespace: test-namespace-37
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ipv6: 'false'
  labels:
    app: test-deployment-name-37
spec:
  type: ClusterIP
  selector:
    app: test-deployment-name-37
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
