apiVersion: v1
kind: Service
metadata:
  name: test-deployment-name-44
  namespace: test-namespace-44
  labels:
    app: test-deployment-name-44
spec:
  type: ClusterIP
  selector:
    app: test-deployment-name-44
  ports:
    - name: TCP
      protocol: TCP
      port: 80
      targetPort: 80
    - name: TCP
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-name-44
  namespace: test-namespace-44
  labels:
    app: test-deployment-name-44
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment-name-44
  template:
    metadata:
      labels:
        app: test-deployment-name-44
    spec:
      containers:
        - name: test-deployment-name-44-container
          image: rabbitmq:management-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: 2Mi
              cpu: '2'
            limits:
              memory: 2Gi
              cpu: '2'
          env:
            - name: NODE_ENV
              value: production
            - name: API_KEY
              value: your-api-key-here
      imagePullSecrets:
        - name: scoutflo-registry-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-deployment-name-44
  namespace: test-namespace-44
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: docker-custom-service-test-test-k-wz.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-deployment-name-44
                port:
                  number: 80
  tls:
    - hosts:
        - docker-custom-service-test-test-k-wz.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
